### PR TITLE
Fixed not working TERM signal

### PR DESCRIPTION
**Pull request by nhayashi**
I fixed not working TERM signal.
see also
https://github.com/kazuho/p5-parallel-prefork/blob/master/lib/Parallel/Prefork.pm#L71
https://metacpan.org/source/MLEHMANN/AnyEvent-7.05/lib/AnyEvent.pm#L1781

### CODE REVIEW

**Comment by kazeburo** [comment]
merged. 

but

```
delete $SIG{TERM};
```

is works?

I added more test on signal.t. please check this
https://github.com/kazeburo/Twiggy-Prefork/commit/b4a4faa232545fadac6c0dc5d40f7070087e2aab

**Comment by kazeburo** [comment]
Oops travis failed.
https://travis-ci.org/kazeburo/Twiggy-Prefork/jobs/10881462

**Comment by kazeburo** [comment]
Sorry. delete $SIG{TERM} works.
test passed on travis-ci.

But test passed when I remove "delete $SIG{TERM}" line on my local machine test. why..?

**Comment by nhayashi** [comment]
Thanks merged my pull request.
I checked you added test code. It's good!

Please tell me AnyEvent, Parallel::Prefork version on your machine.
What is your machine mac? linux?

**Comment by kazeburo** [comment]
Released 0.06

@nhayashi 
I use mac. AnyEvent-7.05 and Parallel-Prefork-0.14.

**Comment by nhayashi** [comment]
I confirmed version 0.06 is released. It's good job!

I tried to reproduce test is failed on mac and same module version, but I couldn't reproduce...

Messages that are output when you run the following code: What is?

``` perl
 61         $pm->start and next;
 62 +      DEBUG && warn "[$$] ".$SIG{TERM};
```

**Comment by kazeburo** [comment]
I found a reason.
If Async::Interrupt is installed, signal.t is able to passing without `delete $SIG{TERM}`

**Comment by nhayashi** [comment]
I understood.
https://metacpan.org/source/MLEHMANN/AnyEvent-7.05/lib/AnyEvent.pm#L1765
This code don't watch SIG{TERM}, and then signals.t test is successed.

**Pull request merged**
